### ISSUE TITLE
Bug: Changing flavor causes "resize loop" on Openstack

### ISSUE THREAD

**Issue by pasettifabio** [crossplane-contrib/provider-openstack#101]
Hi, I'm using Crossplane's OpenStack provider to deploy instances and manage them.

Everything works very well but when I change the flavor (flavorName or flavorId) for instance, it loops through infinite resizing between the original flavor and the new one and again to the original (of course, reducing the size if the original flavor is smaller then the newest...).

This is the instanceV2 manifest:
```
apiVersion: compute.openstack.crossplane.io/v1alpha1
kind: InstanceV2
metadata:
  annotations:
    meta.upbound.io/crossplane01-id: compute/v1alpha1/instancev2
  labels:
    testing.upbound.io/crossplane01-name: node01-test
  name: node01-test
spec:
  providerConfigRef:
    name: openstack-cloudfire-devops
  deletionPolicy: Delete
  forProvider:
    blockDevice:
    - bootIndex: 0
      deleteOnTermination: true
      destinationType: volume
      deviceType:  
      diskBus: ""
      guestFormat: ext4 
      multiattach: false
      sourceType: image 
      uuid: "6f971b3f-7b26-4161-a4a6-9081bbad9667" 
      volumeSize: 15 
      volumeType: Standard
    configDrive: true 
    flavorId: "6c1f1ce7-f356-4dac-b02c-a9b78e9d6d07"
    imageName: "OPERATING_SYSTEM: Ubuntu 22.04 x86_64 Jammy Jellyfish" 
    metadata:
      bootstrapped: "false"
    network:
    - accessNetwork: true
      fixedIpV4: "" 
      fixedIpV6: ""
      floatingIp: ""
      name: private
      port: "" 
      uuid: "" 
    powerState: "active" # active, shutoff, shelved_offloaded
    securityGroups:
    - default
    tags:
    - "instance"
    vendorOptions:
      - detachPortsBeforeDestroy: true
        ignoreResizeConfirmation: true
```
Here you can find the resize loop into Openstack:

Request ID | Action | Start Time | User ID | Message
-- | -- | -- | -- | --
req-9ee2af32-d0cd-49d7-bc3f-44a82c1a4d39 | Resize | May 2, 2024, 9:29 a.m. | ad7d84b9c5934862aca99e3d46806abe | -
req-72dcecfe-9b07-401c-b644-c9e5d688fe2e | Confirm Resize | May 2, 2024, 9:29 a.m. | ad7d84b9c5934862aca99e3d46806abe | -
req-f47d76f6-7bac-49f6-a94b-f1af60f353cc | Resize | May 2, 2024, 9:27 a.m. | ad7d84b9c5934862aca99e3d46806abe | -
req-70d9dba1-528e-49b8-b897-071343f78a61 | Confirm Resize | May 2, 2024, 9:26 a.m. | ad7d84b9c5934862aca99e3d46806abe | -

Does anybody experience the same issue?

Thank you,
Fabio
