### ISSUE TITLE
When creating different components of LoadbalancerV2 there is no cross referencing available

### ISSUE THREAD

**Issue by ankurnema** [crossplane-contrib/provider-openstack#108]
Hello,

I am new to crossplane and trying to use openstack provider.

Our usecase is to create a loadbalancer with multiple listeners, pools, health check etc. For doing this cross-referencing is required.

Lets say I create Loadbalancer using yaml

```yaml
apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: LoadbalancerV2
metadata:
  name: my-lb
  namespace: 
  labels:
    project: my-project
spec:
  forProvider:
    vipSubnetId:  1233acd-2334-1csdds-42342sdscc
  providerConfigRef:
    name: openstack-provider-ref
```
Above will create me a lb by providing vipSubnerId.

Now if I want to create lets say pool then it need [loadbalancerId](https://marketplace.upbound.io/providers/crossplane-contrib/provider-openstack/v0.3.0/resources/lb.openstack.crossplane.io/PoolV2/v1alpha1#doc:spec-forProvider-loadbalancerId) to proceed further.

```yaml
apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: PoolV2
metadata:
  name: my-test-pool
  labels:
    project: my-project
spec:
  forProvider:
    name: test
    lbMethod: ROUND_ROBIN
    loadbalancerId: ??????????
    protocol: HTTPS
  providerConfigRef:
    name: openstack-provider-ref
```

How to get above resource created where my Pool should refer to LB created before. I want to use helm chart to deploy my entire Loadbalancer and all required resources.
