### ISSUE TITLE
Provider manifest in README not working

### ISSUE THREAD

**Issue by pierreprinetti** [crossplane-contrib/provider-openstack#49]
After applying the suggested Provider manifest:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-openstack
spec:
  package: crossplane-contrib/provider-openstack:v0.2.0
```

The provider in Kubernetes stays `INSTALLED: False` indefinitely
